### Post request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name" : "Divya Raj kafka",
  "email" : "drskafkapro@gmail.com",
  "address": "bangalore",
  "registeredDate" : "1998-10-02",
  "dateOfBirth": "1996-10-02"

}

###